services:

  front:
    image: node:22-alpine
    ports:
      - 5173:5173
    volumes:
      - ./app-vite:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    
  directus:
    image: directus/directus:latest
    container_name: directus
    environment:
      #Configuration du port de la DB client (ici pg = postgres) HOST 0.0.0.0 permet d'écouter sur tout les interfacessss reseaux 
      HOST: 0.0.0.0
      PORT: 8055
      DB_CLIENT: pg
      #Ici on dois renseigner le "nom" du service concernée, c'est à dire db utilise postgreSQL alors on met pg (postgreSQL)
      DB_HOST: db
      DB_DATABASE: mydb
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      #Ici on va initialiser l'admin pour directus
      ADMIN_EMAIL: admin@oclock.io
      ADMIN_PAWWORD: oclock
    ports:
      - "8055:8055"
    volumes:
      - ./directus-data:/var/lib/directus
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db